# Configuration for skin lesion segmentation training
optimize: False  # Set to True to run hyperparameter search
data:
  data_path: "./data"
  train_split: 0.8

model:
  num_classes: 1
  learning_rate: 0.001

training:
  max_epochs: 10
  accelerator: "auto"

optuna:
  storage: "sqlite:///optuna.db"
  study_name: "lesion_segmentation_study"
  n_trials: 5
  timeout: 3600

data_module:
  _target_: skin_lesion_segmentation.LesionDataModule
  data_path: ${data.data_path}
  train_split: ${data.train_split}
  img_size: 256
  batch_size: 32
  augmentation: True

logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: "logs"
  name: "default"
  version: "0"

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_dice"
  dirpath: "checkpoints"
  filename: "best"
  save_top_k: 1
  mode: "max"

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_dice"
  patience: 20
  mode: "max"
